# NumPy Arrays 

In [1]:
import numpy as nmp

In [2]:
mylist = [1,2,3,4,6]

In [3]:
type(mylist)

list

In [7]:
arr = nmp.array(mylist) # To conver list to array


In [8]:
arr

array([1, 2, 3, 4, 6])

In [9]:
type(arr)

numpy.ndarray

# creating a matrixs

In [10]:
lst = [[1,2,3],[2,4,5],[6,7,8]]

In [11]:
my_matrix= nmp.array(lst)

In [12]:
my_matrix

array([[1, 2, 3],
       [2, 4, 5],
       [6, 7, 8]])

In [16]:
nmp.arange(0,10,3)

array([0, 3, 6, 9])

In [17]:
nmp.ones(4)

array([1., 1., 1., 1.])

In [21]:
nmp.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
nmp.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
nmp.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
nmp.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
nmp.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [50]:
nmp.random.rand(3,3)

array([[0.32198507, 0.17226949, 0.665019  ],
       [0.82362915, 0.54918256, 0.10301041],
       [0.48591631, 0.05429869, 0.96673686]])

In [52]:
nmp.random.randn(3,3)

array([[ 0.64403372,  1.22228967, -0.07612723],
       [-0.09171736, -0.75279572, -0.64564037],
       [ 1.12708416, -0.50860322, -0.05247353]])

In [64]:
nmp.random.seed(42) # seed can not change the value of outpu with random function .
nmp.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [65]:
nmp.random.randint(1,50,9)

array([39, 19, 23, 11, 11, 24, 36, 40, 24])

In [66]:
nmp.random.seed(100)
nmp.random.rand(4)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

In [67]:
nmp.random.seed(100)
nmp.random.rand(4)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

In [68]:
nmp.random.rand(4)

array([0.00471886, 0.12156912, 0.67074908, 0.82585276])

In [69]:
nmp.random.rand(4)

array([0.13670659, 0.57509333, 0.89132195, 0.20920212])

In [70]:
nmp.random.rand(4)

array([0.18532822, 0.10837689, 0.21969749, 0.97862378])

In [71]:
ary = nmp.arange(50)

In [72]:
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
ary.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [74]:
raray = nmp.arange(1,101,6)

In [75]:
raray

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [79]:
raray.max()

97

In [80]:
raray.min()

1

In [81]:
raray.sum()

833

In [82]:
raray.argmax()

16

In [1]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [7]:
print(dice_rolls.shape)

(29,)
